name: webrtc
channels:
    - defaults
dependencies:
    - python=3
    - pip:
          - aiortc
          - python-socketio[asyncio_client]
          - python-socketio[client]
          - asyncio
          - flask
          - cv2
